### ISSUE TITLE
module 'os' has no attribute 'geteuid'

### ISSUE THREAD

**Issue by achiodza** [bitbrute/evillimiter#1]
So l was fascinated by Evillimiter for educational purposes of course. I used it on my Kali linux and it works so well. I wanted to try it on windows, sadly l got this error

 File "C:\Users\*******\Anaconda3\lib\site-packages\evillimiter-1.1.0-py3.6.egg\evillimiter\evillimiter.py", line 39, in is_privileged
    **return os.geteuid() == 0**
**

> AttributeError: module 'os' has no attribute 'geteuid'

**
![image](https://user-images.githubusercontent.com/17200838/55899519-4670e700-5bc5-11e9-9b54-77782d1b84b8.png)

Any Fix for this

**Comment by bitbrute** [comment]
Thank you.
Unfortunately, **os.getuid()** is a function only available for Unix-like systems. However, even if it would be replaced with a cross-platform alternative, the tool is still going to depend on a lot of functionality only provided by Linux systems, like [tc](https://linux.die.net/man/8/tc) (traffic control) and [iptables](https://linux.die.net/man/8/iptables).

The best thing you can do is sticking to Kali and forgetting about Windows ;)
Have a good one!
