### ISSUE TITLE
I put python3 setup.py install and get this error.

### ISSUE THREAD

**Issue by irunsi** [bitbrute/evillimiter#12]
I put Sudo python3 setup.py install and get this error 

Traceback (most recent call last):
  File “setup.py”, line 3, in <module>
   From setuptools import setup, find_packages, Command
   ModuleNotFoundError: no module named ‘setuptools’

**Comment by hiurequeiroz** [comment]
I had the same problem

**Comment by hiurequeiroz** [comment]
as I see you need do
sudo apt-get install python3-setuptools

**Comment by irunsi** [comment]
Did you do anything after that I got the the same error

**Comment by irunsi** [comment]
> I had the same problem, and solve this way:
> sudo apt-get install python3-setuptools

Didn’t work

**Comment by hiurequeiroz** [comment]
> > I had the same problem, and solve this way:
> > sudo apt-get install python3-setuptools
> 
> Didn’t work

I had other errors, with each error I returned a missing package and then I did 
sudo apt-get install python3-'PKGmissing'

**Comment by irunsi** [comment]
> > > I had the same problem, and solve this way:
> > > sudo apt-get install python3-setuptools
> > 
> > 
> > Didn’t work
> 
> I had other errors, with each error I returned a missing package and then I did
> sudo apt-get install python3-'PKGmissing'

Thanks man although I wish you could do a vid on YouTube if this thankyou though⚡️

**Comment by irunsi** [comment]
> > > I had the same problem, and solve this way:
> > > sudo apt-get install python3-setuptools
> > 
> > 
> > Didn’t work
> 
> I had other errors, with each error I returned a missing package and then I did
> sudo apt-get install python3-'PKGmissing'

By the way we’re do you transfer the files once you have pk and setup tools

**Comment by irunsi** [comment]
> > > I had the same problem, and solve this way:
> > > sudo apt-get install python3-setuptools
> > 
> > 
> > Didn’t work
> 
> I had other errors, with each error I returned a missing package and then I did
> sudo apt-get install python3-'PKGmissing'

Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 11, in <module>
    load_entry_point('evillimiter==1.2.0', 'console_scripts', 'evillimiter')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/evillimiter-1.2.0-py2.7.egg/evillimiter/evillimiter.py", line 157
    IO.print(get_main_banner(version))
           ^
SyntaxError: invalid syntax

**Comment by bitbrute** [comment]
You are using Python 2.7. You want to run it with Python 3.x.
Type ```pip3 install setuptools``` and the run the setup by typing ```python3 setup.py install```
Finally run the tool: ```evillimiter```

**Comment by irunsi** [comment]
> You are using Python 2.7. You want to run it with Python 3.x.
> Type `pip3 install setuptools` and the run the setup by typing `python3 setup.py install`
> Finally run the tool: `evillimiter`

steal got the exact same error i deleted python 2.7 and instaled evil with python3 

root@deabian:~# cd Documents
root@deabian:~/Documents# git clone https://github.com/bitbrute/evillimiter.git
Cloning into 'evillimiter'...
remote: Enumerating objects: 126, done.
remote: Counting objects: 100% (126/126), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 126 (delta 69), reused 98 (delta 43), pack-reused 0
Receiving objects: 100% (126/126), 31.27 KiB | 842.00 KiB/s, done.
Resolving deltas: 100% (69/69), done.
root@deabian:~/Documents# cd evillimiter
root@deabian:~/Documents/evillimiter# sudo python3 setup.py install
/usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/evillimiter
copying evillimiter/__init__.py -> build/lib/evillimiter
copying evillimiter/evillimiter.py -> build/lib/evillimiter
creating build/lib/evillimiter/networking
copying evillimiter/networking/spoof.py -> build/lib/evillimiter/networking
copying evillimiter/networking/host.py -> build/lib/evillimiter/networking
copying evillimiter/networking/__init__.py -> build/lib/evillimiter/networking
copying evillimiter/networking/limiter.py -> build/lib/evillimiter/networking
copying evillimiter/networking/utils.py -> build/lib/evillimiter/networking
copying evillimiter/networking/scan.py -> build/lib/evillimiter/networking
creating build/lib/evillimiter/console
copying evillimiter/console/io.py -> build/lib/evillimiter/console
copying evillimiter/console/shell.py -> build/lib/evillimiter/console
copying evillimiter/console/__init__.py -> build/lib/evillimiter/console
copying evillimiter/console/banner.py -> build/lib/evillimiter/console
creating build/lib/evillimiter/common
copying evillimiter/common/__init__.py -> build/lib/evillimiter/common
copying evillimiter/common/globals.py -> build/lib/evillimiter/common
creating build/lib/evillimiter/menus
copying evillimiter/menus/main_menu.py -> build/lib/evillimiter/menus
copying evillimiter/menus/__init__.py -> build/lib/evillimiter/menus
copying evillimiter/menus/parser.py -> build/lib/evillimiter/menus
copying evillimiter/menus/menu.py -> build/lib/evillimiter/menus
running install_lib
copying build/lib/evillimiter/networking/spoof.py -> /usr/local/lib/python3.7/site-packages/evillimiter/networking
copying build/lib/evillimiter/networking/host.py -> /usr/local/lib/python3.7/site-packages/evillimiter/networking
copying build/lib/evillimiter/networking/__init__.py -> /usr/local/lib/python3.7/site-packages/evillimiter/networking
copying build/lib/evillimiter/networking/limiter.py -> /usr/local/lib/python3.7/site-packages/evillimiter/networking
copying build/lib/evillimiter/networking/utils.py -> /usr/local/lib/python3.7/site-packages/evillimiter/networking
copying build/lib/evillimiter/networking/scan.py -> /usr/local/lib/python3.7/site-packages/evillimiter/networking
copying build/lib/evillimiter/__init__.py -> /usr/local/lib/python3.7/site-packages/evillimiter
copying build/lib/evillimiter/console/io.py -> /usr/local/lib/python3.7/site-packages/evillimiter/console
copying build/lib/evillimiter/console/shell.py -> /usr/local/lib/python3.7/site-packages/evillimiter/console
copying build/lib/evillimiter/console/__init__.py -> /usr/local/lib/python3.7/site-packages/evillimiter/console
copying build/lib/evillimiter/console/banner.py -> /usr/local/lib/python3.7/site-packages/evillimiter/console
copying build/lib/evillimiter/evillimiter.py -> /usr/local/lib/python3.7/site-packages/evillimiter
copying build/lib/evillimiter/common/__init__.py -> /usr/local/lib/python3.7/site-packages/evillimiter/common
copying build/lib/evillimiter/common/globals.py -> /usr/local/lib/python3.7/site-packages/evillimiter/common
copying build/lib/evillimiter/menus/main_menu.py -> /usr/local/lib/python3.7/site-packages/evillimiter/menus
copying build/lib/evillimiter/menus/__init__.py -> /usr/local/lib/python3.7/site-packages/evillimiter/menus
copying build/lib/evillimiter/menus/parser.py -> /usr/local/lib/python3.7/site-packages/evillimiter/menus
copying build/lib/evillimiter/menus/menu.py -> /usr/local/lib/python3.7/site-packages/evillimiter/menus
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/networking/spoof.py to spoof.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/networking/host.py to host.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/networking/__init__.py to __init__.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/networking/limiter.py to limiter.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/networking/utils.py to utils.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/networking/scan.py to scan.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/__init__.py to __init__.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/console/io.py to io.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/console/shell.py to shell.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/console/__init__.py to __init__.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/console/banner.py to banner.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/evillimiter.py to evillimiter.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/common/__init__.py to __init__.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/common/globals.py to globals.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/menus/main_menu.py to main_menu.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/menus/__init__.py to __init__.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/menus/parser.py to parser.cpython-37.pyc
byte-compiling /usr/local/lib/python3.7/site-packages/evillimiter/menus/menu.py to menu.cpython-37.pyc
running install_egg_info
Removing /usr/local/lib/python3.7/site-packages/evillimiter-1.2.0-py3.7.egg-info
Writing /usr/local/lib/python3.7/site-packages/evillimiter-1.2.0-py3.7.egg-info
root@deabian:~/Documents/evillimiter# evillimiter
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 11, in <module>
    load_entry_point('evillimiter==1.2.0', 'console_scripts', 'evillimiter')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/evillimiter-1.2.0-py2.7.egg/evillimiter/evillimiter.py", line 157
    IO.print(get_main_banner(version))
           ^
SyntaxError: invalid syntax
root@deabian:~/Documents/evillimiter# pip3 install setuptools
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (40.8.0)
root@deabian:~/Documents/evillimiter# evillimiter
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 11, in <module>
    load_entry_point('evillimiter==1.2.0', 'console_scripts', 'evillimiter')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/evillimiter-1.2.0-py2.7.egg/evillimiter/evillimiter.py", line 157
    IO.print(get_main_banner(version))

**Comment by rhyxoduzz** [comment]
When i cd to gitdl-master then type (python setup.py install) this is the message File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

**Comment by bitbrute** [comment]
Did you try the solution that was already posted?

**Comment by SamTheSapien** [comment]
I had the same error and tried to dowload that packgage again. It says it already exists. Then when i try to build it again it says it does not find the package. And it does that again and again in a loop.
Can someone help me?

**Comment by abanoub-asaad** [comment]
> I put Sudo python3 setup.py install and get this error
> 
> Traceback (most recent call last):
> File “setup.py”, line 3, in
> From setuptools import setup, find_packages, Command
> ModuleNotFoundError: no module named ‘setuptools’

Try this, worked for me!
sudo apt-get install python3-setuptools

**Comment by yusuf601** [comment]
> I had the same problem, and solve this way: sudo apt-get install python3-setuptools

Thank bro
