### ISSUE TITLE
ip problem

### ISSUE THREAD

**Issue by qwertyhq0x** [bitbrute/evillimiter#127]
for some reason, it does not look for wifi network clients
when searching for all ip start with 10.0.0.0 ...
gateway ip is set as in the screenshot, evillimiter itself
does not see wlan0
after selecting wlan0, it gives an error
with custom parameters, the software works, but does not look for hosts

<img width="612" alt="image" src="https://user-images.githubusercontent.com/83676869/158997003-c249a961-c675-47cd-a7c7-6ffc11dabe41.png">

**Comment by ayoubriahi936** [comment]
aaaaaaaaaa


Le ven. 18 mars 2022 à 16:42, qwertyhq0x ***@***.***> a
écrit :
