### ISSUE TITLE
A new syntax error can some one plz help me with it (traceback) /Traceback (most recent call last):

### ISSUE THREAD

**Issue by irunsi** [bitbrute/evillimiter#13]
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 11, in <module>
    load_entry_point('evillimiter==1.2.0', 'console_scripts', 'evillimiter')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/evillimiter-1.2.0-py2.7.egg/evillimiter/evillimiter.py", line 157
    IO.print(get_main_banner(version))
           ^
SyntaxError: invalid syntax

**Comment by bitbrute** [comment]
You ran EvilLimiter with Python 2.7. But EvilLimiter requires Python 3.x or higher.

**Comment by irunsi** [comment]
> You ran EvilLimiter with Python 2.7. But EvilLimiter requires Python 3.x or higher.

Is there anyway to permnant delete python 2.7 or make python 3 deffault

**Comment by leonardus** [comment]
> > You ran EvilLimiter with Python 2.7. But EvilLimiter requires Python 3.x or higher.
> 
> Is there anyway to permnant delete python 2.7 or make python 3 deffault

On Ubuntu, you can `sudo apt purge python2.7` to permanently delete it. However, this is a bad idea because a lot of software still depends on Python 2.7. You should first try running `pip3 install setuptools`, followed by `python3 setup.py install`, and then check if Evil Limiter works.

**Comment by irunsi** [comment]
> > > You ran EvilLimiter with Python 2.7. But EvilLimiter requires Python 3.x or higher.
> > 
> > 
> > Is there anyway to permnant delete python 2.7 or make python 3 deffault
> 
> On Ubuntu, you can `sudo apt purge python2.7` to permanently delete it. However, this is a bad idea because a lot of software still depends on Python 2.7. You should first try running `pip3 install setuptools`, followed by `python3 setup.py install`, and then check if Evil Limiter works.

now what do I do thankyou for that part
now this error though
by the way if i download PKG_resources were do i move the file to please help. 

Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by irunsi** [comment]
> You ran EvilLimiter with Python 2.7. But EvilLimiter requires Python 3.x or higher.

Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by bitbrute** [comment]
See #15
