### ISSUE TITLE
Finished all the other errors new error says No module named pkg_resources   

### ISSUE THREAD

**Issue by irunsi** [bitbrute/evillimiter#15]

**Comment by irunsi** [comment]
root@deabian:~/Desktop/evillimiter# evillimiter
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
root@deabian:~/Desktop/evillimiter#

**Comment by irunsi** [comment]
evillimiter
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by bitbrute** [comment]
I can't really figure out the issue if there is no background information given (OS, Python Version, ...).
Are you sure you have ```setuptools``` installed for your python version you are trying to execute the script with?
