### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by hussam-dh** [bitbrute/evillimiter#16]
![evillimiter](https://user-images.githubusercontent.com/5878980/59555425-a7001400-8fba-11e9-9fe2-a9caa69b2f46.png)
Hello,
an image of the Errors is attached.

My OS: Fedora 25 64bit
I checked the first three Errors and the  mentioned utils were in the PATH.

Regards

**Comment by leonardus** [comment]
What is the output of `which tc` and `echo $PATH`?

**Comment by hussam-dh** [comment]
which tc:
/usr/sbin/tc
echo $PATH:
/root/.local/bin:/root/projects/bin:/opt/go/bin:/root/.local/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/var/lib/snapd/snap/bin:/bin:/root/go/bin:/opt/apache-ant-1.10.5/bin:/root/bin:/opt/go/bin:/root/go/bin:/opt/apache-ant-1.10.5/bin

**Comment by leonardus** [comment]
Have you changed the PATH recently?

By the way, the site you linked contains malicious advertising (see the images below. uMatrix shows me that the adware is coming from the domain `shermore.info`). GitHub allows you to attach files, so please use that next time you need to share a screenshot.

[Screenshot](https://user-images.githubusercontent.com/23728094/59555316-4f43b780-8f7e-11e9-96ea-2a2fc215ba35.jpg)
[uMatrix](https://user-images.githubusercontent.com/23728094/59555322-54086b80-8f7e-11e9-82ee-1572957b8d98.png)

**Comment by hussam-dh** [comment]
so sorry for that site, will not use it again.

about changing the PATH, actually I don't remember changing it,
but why asking about that?

Regards

**Comment by leonardus** [comment]
I cannot reproduce this bug on a Fedora 25 Workstation VM.

![image](https://user-images.githubusercontent.com/23728094/59555609-1528e480-8f83-11e9-9f44-17f599632446.png)

**Comment by hussam-dh** [comment]
Hello,
Thank you very much, I solved the issue by editing this file:
build/lib/evillimiter/console/shell.py
to be like this:
![evil2](https://user-images.githubusercontent.com/5878980/59555841-eed66980-8fc1-11e9-862c-4bfe3eee3188.png)

Thank you very much
