### ISSUE TITLE
Interface Err

### ISSUE THREAD

**Issue by mondocrypto** [bitbrute/evillimiter#17]
Getting this error. 
ERR  default interface could not be resolved. specify manually (-i).

**Comment by leonardus** [comment]
Determine your network interface using `route` or `ifconfig`, and pass the interface name to evillimiter with `-i`.

**Comment by patience0721** [comment]
im on ubuntu 20.04 LTS . and i sloved this error by using this COMMAND  sudo evillimiter --flush . try maybe its work fo you alos
