### ISSUE TITLE
Consider adding option to block via MAC

### ISSUE THREAD

**Issue by Muhammad-Daniyal-Sheikh** [bitbrute/evillimiter#18]
Please consider adding an option to block a host via their MAC, it would be quite useful, perhaps something like this:
`block [INSERT MAC HERE]`

**Comment by leonardus** [comment]
Submitted a PR for this #19

**Comment by bitbrute** [comment]
The PR has been comitted to the develop branch and will soon be pushed to master with the next update. See 4d7c98b

**Comment by Muhammad-Daniyal-Sheikh** [comment]
Closing issue.
