### ISSUE TITLE
Network help.

### ISSUE THREAD

**Issue by casiem59** [bitbrute/evillimiter#25]
So apparently when I scan it only shows 3 hosts and those IP address are incorrect my interface is eth0 but my gateway ip and gateway Mac is incorrect is there anyway to change the gateway ip and gateway Mac I tried doing it by evil limiter -m (gateway Mac) and evil limiter -h and I put it my router gateway Mac and IP but when I input the Mac it auto starts evil limiter but not with the settings I put in the same incorrect ones

**Comment by casiem59** [comment]
What I mean is do I need to go to wifi and disable IPv6? Cause when I go onto limiter it's only detecting 3 HOSTS but when I turn off my wifi off my phone and scan again still says 3 hosts with the same IP mine starts with 192 it's starting with 10.11 something .

**Comment by casiem59** [comment]
So now I'm connected to my wifi, disabled IPv6 0k so now I load evillimiter when I load it it says interface eth0 which is correct BUT evillimiter should automatically do gateway ip and gateway Mac right? So instead of THAT it puts in the incorrect gateway ip and gateway Mac so when i put in my gateway ip  and gateway which is my router MAC address and I scan it says 0 hosts??? So I'm very confused .

**Comment by bitbrute** [comment]
Are you sure that the gateway MAC and IP address is invalid? 
If so, parameter ```-g``` specifies gateway IP and parameter ```-m``` specifies gateway MAC.

Maybe your hosts are on a different subnet. You can specify a custom IP range when scanning (```--range```).

**Comment by safwen010** [comment]
hi , so im  using evilimiter to limit my friend uses on my airbox, but it is not showing all hosts ,
can u help me

**Comment by Benyaminhaghighatshoar** [comment]
Bro bitbrute pls me to when ever I scan it shows 3 hosts with wrong ip I'm new to this so pls smone help me

**Comment by endafk** [comment]
I'm not more of a Techie but I scan the network using nmap so that i can compare that to the number of scanned hosts
`nmap -sn 10.0.0.0/24` 
 where 10.0.0.0 is the gateway address.

If the number of hosts found appears to be less than the nmap ones, I tend to wait a bit then rescan: Always works
![Screenshot from 2024-05-14 20-26-15](https://github.com/bitbrute/evillimiter/assets/68908122/6e7d3bdf-3e5e-4c61-b002-82a746eed739)
