### ISSUE TITLE
Does limit and block really block and limit the users?cause i see no effect?

### ISSUE THREAD

**Issue by falconblackburn** [bitbrute/evillimiter#28]
Does limit and block really block and limit the users cause I see no effect, the wifi still works perfectly and the normal speed

**Comment by bitbrute** [comment]
There are many reasons why EvilLimiter may not work as described.

1. Are the resolved gateway addresses correct?
2. Is there an AV solution installed on the target machine that detects the "attack"?
3. Are you sure ARP packets - required for spoofing the target - are actually leaving your machine?
4. Can you monitor ARP packets "entering" the target machine?
...

**Comment by bitbrute** [comment]
See #6
