### ISSUE TITLE
no module named 'netifaces'

### ISSUE THREAD

**Issue by mcdert** [bitbrute/evillimiter#30]
i already search everywhere, and didn't get any solution

Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 11, in <module>
    load_entry_point('evillimiter==1.2.0', 'console_scripts', 'evillimiter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/evillimiter-1.2.0-py3.7.egg/evillimiter/evillimiter.py", line 9, in <module>
    import evillimiter.networking.utils as netutils
  File "/usr/local/lib/python3.7/dist-packages/evillimiter-1.2.0-py3.7.egg/evillimiter/networking/utils.py", line 2, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'

**the weird thing is, i already have module netifaces on pip3**

user@computer:~/evillimiter-1.2.0$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
Brlapi (0.6.6)
certifi (2018.1.18)
chardet (3.0.4)
colorama (0.4.1)
cryptography (2.1.4)
cupshelpers (1.0)
defer (1.0.6)
distro-info (0.18ubuntu0.18.04.1)
evillimiter (1.2.0)
httplib2 (0.9.2)
idna (2.6)
keyring (10.6.0)
keyrings.alt (3.0)
launchpadlib (1.10.6)
lazr.restfulclient (0.13.5)
lazr.uri (1.0.3)
louis (3.5.0)
macaroonbakery (1.1.3)
Mako (1.0.7)
MarkupSafe (1.0)
netaddr (0.7.19)
**netifaces (0.10.4)**
oauth (1.0.1)
olefile (0.45.1)
pexpect (4.2.1)
Pillow (5.1.0)
pip (9.0.1)
protobuf (3.0.0)
pycairo (1.16.2)
pycrypto (2.6.1)
pycups (1.9.73)
pygobject (3.26.1)
pymacaroons (0.13.0)
PyNaCl (1.1.2)
pyRFC3339 (1.0)
python-apt (1.6.4)
python-dateutil (2.6.1)
python-debian (0.1.32)
pytz (2018.3)
pyxdg (0.25)
PyYAML (3.12)
reportlab (3.4.0)
requests (2.18.4)
requests-unixsocket (0.1.5)
scapy (2.4.3)
scapy-python3 (0.23)
screen-resolution-extra (0.0.0)
SecretStorage (2.3.1)
setuptools (39.0.1)
simplejson (3.13.2)
six (1.11.0)
systemd-python (234)
terminaltables (3.1.0)
tqdm (4.35.0)
ubuntu-drivers-common (0.0.0)
ufw (0.36)
unattended-upgrades (0.1)
urllib3 (1.22)
usb-creator (0.3.3)
wadllib (1.3.2)
wheel (0.33.6)
xkit (0.0.0)
zope.interface (4.3.2)

**Comment by jordantsap** [comment]
pip3 install netifaces and if there is an error output sudo apt install python3-dev first
