### ISSUE TITLE
Limit command just block devices not limiting the speed

### ISSUE THREAD

**Issue by iqrulltion** [bitbrute/evillimiter#33]
limit command just block devices " no internet " not limiting network speed , i tested that on 2 devices with different OS , from the router wifi and the access point wifi  even with different speed .. same results although the device on the terminal is limited .

Linux Mint 19.1

**Comment by bitbrute** [comment]
When you limit a device, can you try to capture network traffic coming from the limited device?
Are you sure IP forwarding is enabled (```sysctl net.ipv4.ip_forward``` should output ```1``` when limiting)?

**Comment by iqrulltion** [comment]
the old output : 
```
net.ipv4.ip_forward = 1
net.ipv4.ip_forward_use_pmtu = 0
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.anbox0.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.enp9s0.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
sysctl: reading key "net.ipv6.conf.wlp8s0.stable_secret"

```
the new output after using

```
sysctl -w net.ipv4.ip_forward=1
net.ipv4.ip_forward = 1 : 
```

is
```
net.ipv4.ip_forward = 1
```

so it is enabled, i tested limiting again but same results, i will upload a log from wireshark ARP protocol .. ( the target device , router . Linux device " )

tell me if other info is required 
  
[LOG.tar.gz](https://github.com/bitbrute/evillimiter/files/3622228/LOG.tar.gz)

thanks

**Comment by bitbrute** [comment]
IP forwarding is enabled and the ARP traffic log looks good to me.
Could you capture any TCP traffic that was dedicated to or sent by the limited device? If not, there is a probabling with forwarding the traffic.
Do you have some kind of special / different subnet? Are you connected to dLAN or a repeater by any chance?

**Comment by bitbrute** [comment]
One more thing:
Try to run EvilLimiter with the ```--flush``` flag. Maybe there are firewall rules that drop forwarded traffic.

**Comment by iqrulltion** [comment]
first i can say the problem solved but limiting not working as i expected not sure if that normal so i have some questions 

but first the details:
`Do you have some kind of special / different subnet? Are you connected to dLAN or a repeater by any chance?`

i am using custom DNS on Linux device not the ISP/the router DNS, the ironic side i was thinking about that at the beginning but at that i saw the DNS was automatic and i can see the default DNS included so i hesitated and then i just ignored that. but any way after deleting the custom DNS i think limiting worked but i have some questions.

1- first time it worked as i remember the speed was more than the "limited if limited" for example 400-900kbit the speed  on the deicemaybe  2-3 mbit **sometimes it goes to more than that near to "MAX speed" ** some time at the range **is that normal ?**

2-  i found " no internet" on the device after period of time but after reconnecting the device and rescan on evillimiter that was fixed **is that normal ?**

but anyway i did not have much time to test that more at the time of posting this post so i might update that before your reply 

thanks

**Comment by iqrulltion** [comment]
final update : **the limiting only work** when i use WIFI from the router not from the access point (linked to the router)  and with the default DNS .. and when i am using the router WIFI on evillimter sometimes you need to scan more than one time to show all hosts but with using the access point the scan is more efficient but that is not the problem here.

so what is your comment on that ? and the questions above.

if that required i might upload logs of all protocols using wireshark using the router and the access point.

**Comment by bitbrute** [comment]
> 1- first time it worked as i remember the speed was more than the "limited if limited" for example 400-900kbit the speed on the device maybe 2-3 mbit **sometimes more than that near to "MAX speed"** sometime at the range **is that normal ?**
> 
> 2- i found " no internet" on the device after period of time but after reconnecting the device and rescan on evillimiter that was fixed **is that normal ?**

1. That is definitely not normal. Usually the rate should be either below or just slightly above the limitation.<br>How did you measure the speed? It should be measured over a longer period of time (5-6s at minumum) to get an average.<br>That's because there is something called a *burst*, where traffic can be sent at max. speed but just over a very short time, until the limitation kicks in (depending on the burst size).

2. By "no internet", do you mean the traffic was blocked or did you fully disconnect from your network? However, either of those should not happen.

Unfortunately, I'm not able to reproduce the issues you listed.
<br>

> when i am using the router WIFI on evillimter sometimes you need to scan more than one time to show all hosts but with using the access point the scan is more efficient

I noticed that myself. Sometimes hosts are missing, because of the sloppy scan. The faster the scan, the sloppier the results.<br>Soon you will be able to specify the scan accuracy (either *fast and unaccurate* or *slow and accurate*).

**Comment by iqrulltion** [comment]
scan point:
i think i have explanation for the scan point maybe because the router single is weaker than access point beside i noticed as i remember the delay is with devices that using the access point but that is not the problem here and it can be fixed by rescan.  

not internet point :  i think that was temporary or not a problem that i will face this  about the router not the access point the limiting using the access point not working at all

limiting and speed point :
i just tested again " limiting" using the router WIFI and custom DNS with automatic option the limiting worked and that is strange because i tried that before and did not work and after changing that it worked so i do not know how or maybe after enabling IP forwarding but if because that only i tested limiting after that and did not work .. **so i am not sure what step exactly fixed it**

but just to keep the facts and taking step forward : **the limiting works**  and i think in less than minute the speed goes down even more lower than than " limited speed" and i made sure the device is effected by the " attack or limiting " by freeing it  immediately ..

**the access point point :** 
at least for the points above the results not that bad at least for me but for the access point 

 why blocking working fine but limiting not working ?

**Comment by iqrulltion** [comment]
Update : No internet / The access point / Limiting / issues are fixed even the speed (test) the result is logical.

after using ! ` sudo evillimiter --flush` sorry that i did not test that earlier even sorry for myself.

Thanks

**Comment by bitbrute** [comment]
I never thought about that ;).
I'm going to include an admin-check, so that will never happen again.

Issue will be closed after the fix.
Thank you!
