### ISSUE TITLE
Can't free my own laptop

### ISSUE THREAD

**Issue by c4iro** [bitbrute/evillimiter#35]
I blocked my laptop to try out the tool, after i did so i tried to free it but kali froze and had to hard reboot it. Now when i started evillimiter my laptop doesn't show up in the hosts list, thus i can't free it. HELP

**Comment by bitbrute** [comment]
Usually, the connection of the machine you blocked will be restored automatically. Freeing a device just speeds up the process.
If it doesn't work even after some time has passed, reboot your laptop.
