### ISSUE TITLE
evillimiter on termux 

### ISSUE THREAD

**Issue by Rafael478** [bitbrute/evillimiter#36]
hi
i tried to install the tool on termux and i did it 
but when i try to start use it by thia command : evillimiter 
it gives me this 
root@localhost:~# evillimiter
ERR  missing util: tc, check your PATH
ERR  missing util: iptables, check your PATH
ERR  missing util: sysctl, check your PATH

███████╗██╗   ██╗██╗██╗       ██╗     ██╗███╗   ███╗██╗████████╗███████╗██████╗
██╔════╝██║   ██║██║██║       ██║     ██║████╗ ████║██║╚══██╔══╝██╔════╝██╔══██╗
█████╗  ██║   ██║██║██║       ██║     ██║██╔████╔██║██║   ██║   █████╗  ██████╔╝
██╔══╝  ╚██╗ ██╔╝██║██║       ██║     ██║██║╚██╔╝██║██║   ██║   ██╔══╝  ██╔══██╗
███████╗ ╚████╔╝ ██║███████╗  ███████╗██║██║ ╚═╝ ██║██║   ██║   ███████╗██║  ██║
╚══════╝  ╚═══╝  ╚═╝╚══════╝  ╚══════╝╚═╝╚═╝     ╚═╝╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝
                by bitbrute  ~  limit devices on your network :3
                                    v1.3.0

ERR  default interface could not be resolved. specify manually (-i).
can you help me please

**Comment by bitbrute** [comment]
EvilLimiter does not and will never work on any Linux emulators.
However, the error messages are kind of misleading and will be fixed soon.

Thank you
