### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kattking16** [bitbrute/evillimiter#37]
rootk@LAPTOP-M25MSLPJ:~/evillimiter$ python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages, Command
ModuleNotFoundError: No module named 'setuptools'

**Comment by leonardus** [comment]
Duplicate of #12. 
Solution:
> Type `pip3 install setuptools` and the run the setup by typing `python3 setup.py install`
> Finally run the tool: `evillimiter`
