### ISSUE TITLE
Not Limiting connections, Completely blocks connections.

### ISSUE THREAD

**Issue by TizTheWiz** [bitbrute/evillimiter#40]
Im unsure what happened. When i first installed evil limiter and tested it. It was limiting the connections to 3mbits with the limit command. Now if i run the limit command, it completely blocks the device from loading web pages as if i used the block command. I have tried with ethernet, it worked to limit connections. And my built in wireless device also was limiting the connections. So im confused as to why it just stopped functioning. Any ideas?

**Comment by bitbrute** [comment]
See #33
