### ISSUE TITLE
Block by Mac Address not IP Address

### ISSUE THREAD

**Issue by jeffward01** [bitbrute/evillimiter#43]
First of all great tool!! Thanks for the great work on this amazing tool. 

I have seen that when a user “limits” or blocks traffic the EvilLimiter application blocks by IP address. 

• The blocked user then experiences limited speed. 

The issue is that:

• the blocked user experiences limited speed, then drops off from the Network, then reconnects. The blocked user is assigned a new IP address and the MAC address remains. 

This makes it so if I “limit” my entire network, and someone is “disconnecting then reconnecting” they are able to bypass the EvilLimiter. 

If the EvilLimiter blocked/limited by Mac Address instead of IP address this workaround for blocked users would be more difficult

**Comment by leonardus** [comment]
You can use the block/limit command followed by a MAC address instead of an IP address or an ID.

**Comment by bitbrute** [comment]
Even though you can block devices by MAC address, they will not be blocked when reconnecting with a different IP. 
As of now, this is not possible. But I'm planning on adding a "watch" command that periodically scans for a given MAC address and thus detects reconnects. Will work on that when I have the time!

**Comment by bitbrute** [comment]
I know, some time has passed, but there it is 46d2033b022f4a51fb2f419393a5344ad3edea4a :)
