### ISSUE TITLE
ipv6 bug

### ISSUE THREAD

**Issue by FedeIPFS** [bitbrute/evillimiter#44]
so, i tested it on my phone and apps like telegram or youtube couldn't access the internet, but whenever i tried to visit ipv6.google.com, the blocking effect just disappeared.

**Comment by bitbrute** [comment]
As stated in the [Restrictions](https://github.com/bitbrute/evillimiter/blob/master/README.md#restrictions) section in the README, EvilLimiter does not work for IPv6.
