### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by davex2012** [bitbrute/evillimiter#46]
Hei, I'm running Evillimiter on Kali VM workstation and every time i used EL to limit other devices i can't used my Main computer ( Win 10 ) i don't know why. Suggestion?
![evl](https://user-images.githubusercontent.com/15570883/69497337-2683fe80-0edc-11ea-8456-9aea37885cdc.PNG)

**Comment by bitbrute** [comment]
What are your network settings for the virtual machine? 
Are you using a bridged network connection or NAT?

**Comment by davex2012** [comment]
> What are your network settings for the virtual machine?
> Are you using a bridged network connection or NAT?

Late reply but i'm using NAT
![vm](https://user-images.githubusercontent.com/15570883/76895564-9d1b8200-6866-11ea-8339-472cdf001eac.PNG)

**Comment by bitbrute** [comment]
Tick _Bridged_ instead of _NAT_ in the _Network connection_ group box to integrate your VM into your actual subnet.
That should solve the problem.
