### ISSUE TITLE
Unable to install:

### ISSUE THREAD

**Issue by ibeXedi** [bitbrute/evillimiter#47]
evillimiter$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages, Command
ModuleNotFoundError: No module named 'setuptools'

**Comment by jordantsap** [comment]
Just install setup-tools

**Comment by p5kRNKzT** [comment]
You will need to install python3-pip first. Running `sudo apt install python3` won't do the job. Run `sudo apt install python3-pip` and then try `sudo python3 setup.py install` again

**Comment by bitbrute** [comment]
> Just install setup-tools

... by typing ```python3 -m pip install setuptools```.
