### ISSUE TITLE
Limiter doesn't work

### ISSUE THREAD

**Issue by JtheLyn** [bitbrute/evillimiter#48]
When I do `scan` I only get 3 hosts every time, none of which start with 192.168 instead they start with 10.0.

I worked around this issue by manually adding my own ip and MAC address `add [IP] (--mac [MAC])` then `limit 3 100kbit`

When I checked on speedtest.net the download and upload speeds were not affected even after doing `limit 3 100kbit --download`

**Comment by bitbrute** [comment]
1. Have your selected the correct network interface?
2. Are you running Linux on a VM? If so, are you connected via NAT? You should always establish a bridged network connection.

**Comment by willemijns** [comment]
Hello,

The same 

```
(Main) >>> block 0
OK   192.168.XXX.1 upload / download blocked.
```

and i can write to you :-X

**Comment by f1vefour** [comment]
I have the same issue with devices not being shown but if I scan again I receive a more complete list.

Remember if you have ipv6 support on your network (which I do) there will be issues, arp will not report those using ipv6.

**Comment by willemijns** [comment]
i'm only in IPV4 ;)

**Comment by willemijns** [comment]
FYI i use lubuntu 18.04 LTS and i suppose than this script uses "tc"... maybe tc have new commandline 
parameters ?

**Comment by f1vefour** [comment]
I don't think that is the problem, I'm running Debian Stretch which likely uses an older version of iproute2.

```
apt-cache policy iproute2
iproute2:
  Installed: 4.9.0-1+deb9u1
  Candidate: 4.9.0-1+deb9u1
  Version table:
     4.20.0-2~bpo9+1 100
        100 http://ftp.debian.org/debian stretch-backports/main armhf Packages
 *** 4.9.0-1+deb9u1 500
        500 http://ftp.debian.org/debian stretch/main armhf Packages
        100 /var/lib/dpkg/status
```

**Comment by avanshee** [comment]
I have similar issue, I am able to completely block the connected devices with 
> block 1
also free them as well, but the limit feature is not working with individual devices even if I get a success message

> limit 1 2kbit

OK   10.3.141.220 upload / download limited to 2kbit.

Can anyone please tell me where is it going wrong?

**Comment by bitbrute** [comment]
@f1vefour 
Sometimes devices take a long time to repsond to an ARP request and thus will not be detected. I'm planning on adding a feature that lets your specify the time to wait for a response. E.g. quick / medium / intense scan.

@avanshee 
Maybe #33 helps you out. Feel free to get back to me if none of the solutions work for you.

**Comment by DontKnows** [comment]
> 1. Have your selected the correct network interface?
> 2. Are you running Linux on a VM? If so, are you connected via NAT? You should always establish a bridged network connection.

i am running it on VM, i also set my network settings onto Bridged network, but why i can't limit or even block?
