### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by n3gwg** [bitbrute/evillimiter#49]
Developers,

First let me say to everyone thank you for such a very nice and interesting piece of software! However, I am wondering, is there a way that it evil limiter could monitor the bandwidth and display it for all users before any limits are applied?

Thanks!

Stuart

**Comment by SirJosh3917** [comment]
I would also like a feature that allows you to view the traffic of all clients, even if there are no limits applied.

**Comment by f1vefour** [comment]
That isn't possible, the devices must first be redirected through the device running evillimiter.
