### ISSUE TITLE
can not install 

### ISSUE THREAD

**Issue by willemijns** [bitbrute/evillimiter#50]
Hello, on LUBUNTU 18.04 LTS

`python3 setup.py install`

gives 

Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages, Command
ModuleNotFoundError: No module named 'setuptools'

**Comment by willemijns** [comment]
I installed "pip install setuptools" , the same :-(

**Comment by Larryun** [comment]
Try `sudo apt-get install python3-setuptools`

**Comment by willemijns** [comment]
Yep ;)

```
sudo apt-get install git
sudo apt-get install python3-setuptools
git clone https://github.com/bitbrute/evillimiter.git
cd evillimiter
sudo python3 setup.py install
cd bin
sudo evillimiter

```
