### ISSUE TITLE
Sudo Python3 setup.py isnt working

### ISSUE THREAD

**Issue by Lax3r** [bitbrute/evillimiter#51]
every time i try using it when i get to the first part which is the installation, i get stuck because every time i use `sudo python3 setup.py install` it says this 

> Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages, Command
ModuleNotFoundError: No module named 'setuptools'

can i get help please

**Comment by f1vefour** [comment]
Install the package **python3-setuptools**

**Comment by bitbrute** [comment]
```pip3 install setuptools``` should do the job.
