### ISSUE TITLE
Failing at SUDO PYTHON3 SETUP.PH INSTALL

### ISSUE THREAD

**Issue by asdnwolf** [bitbrute/evillimiter#52]
When i am running the command i receive the following error.

`checking for netlink support...yes. 
will use netlink to read routing table
netifaces.c:1:10: fatal error: Python.h: No such file or directory
    1 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

All attempts to use the tool fail after that as it is missing the netifaces distribution.

**Comment by Tbay005** [comment]
Have the same problem

**Comment by bitbrute** [comment]
What OS / distro are you using?

**Comment by ali765b** [comment]
> What OS / distro are you using?

linux mint

**Comment by mushonnip** [comment]
I solve this problem in Deepin 15.11 by installing python3-dev
`sudo apt-get install python3-dev`

**Comment by CRO-THEHACKER** [comment]
`sudo apt-get install python-dev`

### If that dosent work:

`sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev libssl-dev

sudo easy_install greenlet

sudo easy_install gevent`

**Comment by bitbrute** [comment]
Would appreciate a feedback if a solution has been found.
