### ISSUE TITLE
stuck at sudo python3 setup.py install

### ISSUE THREAD

**Issue by Salah-Zkara** [bitbrute/evillimiter#53]
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages, Command
ModuleNotFoundError: No module named 'setuptools'

**Comment by CRO-THEHACKER** [comment]
### To install setuptools on Debian:

sudo apt-get install python-setuptools

### For Python 3.5.x:

sudo apt-get install python3_(.5)_-setuptools

**Comment by Salah-Zkara** [comment]
~$ sudo apt-get install python3.8-setuptools
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

**Comment by Salah-Zkara** [comment]
already installed and don't even worked.

**Comment by Salah-Zkara** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-setuptools is already the newest version (39.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by rshopnil** [comment]
What system are you running? Try running `uname -a` to find out specific details.

You should get a fix by installing setuptools using

`sudo apt-get install -y python-setuptools`

If you're running Python3, change the above to

`sudo apt-get install -y python3-setuptools`

Finally, if none works, try running

`sudo apt-get install python-pip`

**Comment by mkeen31** [comment]
Still not working for me, I have Python 3.8 and tried running CRO-THEHACKER's solution but it kept giving me an error

**Comment by rshopnil** [comment]
@mkeen31 Please copy your error and post it here using appropriate markdown.

**Comment by mkeen31** [comment]
`Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages, Command
ModuleNotFoundError: No module named 'setuptools'
`

**Comment by mkeen31** [comment]
And this occurs even after I uninstall and reinstall python3-setuptools

**Comment by mkeen31** [comment]
Nevermind I realized it was my Python version. I fixed it now

**Comment by CRO-THEHACKER** [comment]
Someone should close this, **[FIXED]** Issue
