### ISSUE TITLE
This isn't working for me! Blocking isn't working!

### ISSUE THREAD

**Issue by Bobowonnell** [bitbrute/evillimiter#57]
So whenever I scan the IPs show up but whenever I used the block also nothing happens to any devices on the internet. I'm not that good with this may I have some further guidance for this please? Thanks in advance!

**Comment by bitbrute** [comment]
We have several issues reporting this. I redirect everybody to #6.
Feel free to comment on the issue including more details (OS, VM or not, device types, ...).
