### ISSUE TITLE
haw to fix pkg_resources.DistributionNotFound: The 'netifaces' distribution was not found and is required by evillimiter?

### ISSUE THREAD

**Issue by OthtiQ** [bitbrute/evillimiter#58]
root@kali:~/Desktop/evillimiter# evillimiter
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'netifaces' distribution was not found and is required by evillimiter
root@kali:~/Desktop/evillimiter#

**Comment by JasurFugen** [comment]
Hello! i have problem during setup


[root@GameBase evillimiter-1.4.0]# python2 setup.py install
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing requirements to evillimiter.egg-info/requires.txt
writing evillimiter.egg-info/PKG-INFO
writing top-level names to evillimiter.egg-info/top_level.txt
writing dependency_links to evillimiter.egg-info/dependency_links.txt
writing entry points to evillimiter.egg-info/entry_points.txt
reading manifest file 'evillimiter.egg-info/SOURCES.txt'
writing manifest file 'evillimiter.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/evillimiter
copying build/lib/evillimiter/evillimiter.py -> build/bdist.linux-x86_64/egg/evillimiter
copying build/lib/evillimiter/__init__.py -> build/bdist.linux-x86_64/egg/evillimiter
creating build/bdist.linux-x86_64/egg/evillimiter/common
copying build/lib/evillimiter/common/globals.py -> build/bdist.linux-x86_64/egg/evillimiter/common
copying build/lib/evillimiter/common/__init__.py -> build/bdist.linux-x86_64/egg/evillimiter/common
creating build/bdist.linux-x86_64/egg/evillimiter/console
copying build/lib/evillimiter/console/banner.py -> build/bdist.linux-x86_64/egg/evillimiter/console
copying build/lib/evillimiter/console/io.py -> build/bdist.linux-x86_64/egg/evillimiter/console
copying build/lib/evillimiter/console/shell.py -> build/bdist.linux-x86_64/egg/evillimiter/console
copying build/lib/evillimiter/console/__init__.py -> build/bdist.linux-x86_64/egg/evillimiter/console
creating build/bdist.linux-x86_64/egg/evillimiter/menus
copying build/lib/evillimiter/menus/main_menu.py -> build/bdist.linux-x86_64/egg/evillimiter/menus
copying build/lib/evillimiter/menus/menu.py -> build/bdist.linux-x86_64/egg/evillimiter/menus
copying build/lib/evillimiter/menus/parser.py -> build/bdist.linux-x86_64/egg/evillimiter/menus
copying build/lib/evillimiter/menus/__init__.py -> build/bdist.linux-x86_64/egg/evillimiter/menus
creating build/bdist.linux-x86_64/egg/evillimiter/networking
copying build/lib/evillimiter/networking/host.py -> build/bdist.linux-x86_64/egg/evillimiter/networking
copying build/lib/evillimiter/networking/limit.py -> build/bdist.linux-x86_64/egg/evillimiter/networking
copying build/lib/evillimiter/networking/monitor.py -> build/bdist.linux-x86_64/egg/evillimiter/networking
copying build/lib/evillimiter/networking/scan.py -> build/bdist.linux-x86_64/egg/evillimiter/networking
copying build/lib/evillimiter/networking/spoof.py -> build/bdist.linux-x86_64/egg/evillimiter/networking
copying build/lib/evillimiter/networking/utils.py -> build/bdist.linux-x86_64/egg/evillimiter/networking
copying build/lib/evillimiter/networking/__init__.py -> build/bdist.linux-x86_64/egg/evillimiter/networking
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/evillimiter.py to evillimiter.pyc
  File "build/bdist.linux-x86_64/egg/evillimiter/evillimiter.py", line 157
    IO.print(get_main_banner(version))
           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/evillimiter/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/common/globals.py to globals.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/common/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/console/banner.py to banner.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/console/io.py to io.pyc
  File "build/bdist.linux-x86_64/egg/evillimiter/console/io.py", line 26
    def print(text, end='\n', flush=False):
            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/evillimiter/console/shell.py to shell.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/console/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/menus/main_menu.py to main_menu.pyc
  File "build/bdist.linux-x86_64/egg/evillimiter/menus/main_menu.py", line 151
    IO.print(table.table)
           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/evillimiter/menus/menu.py to menu.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/menus/parser.py to parser.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/menus/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/networking/host.py to host.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/networking/limit.py to limit.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/networking/monitor.py to monitor.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/networking/scan.py to scan.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/networking/spoof.py to spoof.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/networking/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/evillimiter/networking/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying evillimiter.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evillimiter.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evillimiter.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evillimiter.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evillimiter.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying evillimiter.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/evillimiter-1.4.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing evillimiter-1.4.0-py2.7.egg
Removing /usr/lib/python2.7/site-packages/evillimiter-1.4.0-py2.7.egg
Copying evillimiter-1.4.0-py2.7.egg to /usr/lib/python2.7/site-packages
evillimiter 1.4.0 is already the active version in easy-install.pth
Installing evillimiter script to /usr/bin

Installed /usr/lib/python2.7/site-packages/evillimiter-1.4.0-py2.7.egg
Processing dependencies for evillimiter==1.4.0
Searching for netifaces
Reading https://pypi.python.org/simple/netifaces/
Best match: netifaces 0.10.9
Downloading https://files.pythonhosted.org/packages/0d/18/fd6e9c71a35b67a73160ec80a49da63d1eed2d2055054cc2995714949132/netifaces-0.10.9.tar.gz#sha256=2dee9ffdd16292878336a58d04a20f0ffe95555465fee7c9bd23b3490ef2abf3
Processing netifaces-0.10.9.tar.gz
Writing /tmp/easy_install-fwYj5W/netifaces-0.10.9/setup.cfg
Running netifaces-0.10.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-fwYj5W/netifaces-0.10.9/egg-dist-tmp-Zwpo4W
checking for getifaddrs...found. 
checking for getnameinfo...found. 
checking for IPv6 socket IOCTLs...not found. 
checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25.h neteconet/ec.h netipx/ipx.h netpacket/packet.h linux/irda.h linux/atm.h linux/llc.h linux/tipc.h linux/dn.h. 
checking whether struct sockaddr has a length field...no. 
checking which sockaddr_xxx structs are defined...at ax25 in in6 ipx un ash ec ll atmpvc atmsvc dn irda llc. 
checking for routing socket support...no. 
checking for sysctl(CTL_NET...) support...no. 
checking for netlink support...yes. 
will use netlink to read routing table
netifaces.c:1:20: фатальная ошибка: Python.h: Нет такого файла или каталога
 #include <Python.h>
                    ^
компиляция прервана.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by JasurFugen** [comment]
how to fix this guys? help please

**Comment by JasurFugen** [comment]
i Solved this problem

**Comment by JasurFugen** [comment]
but after this i recive this problem
when start evillmiter



evillimiter-1.4.0]# evillimiter
Traceback (most recent call last):
  File "/usr/bin/evillimiter", line 9, in <module>
    load_entry_point('evillimiter==1.4.0', 'console_scripts', 'evillimiter')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/evillimiter-1.4.0-py2.7.egg/evillimiter/evillimiter.py", line 157
    IO.print(get_main_banner(version))
           ^
SyntaxError: invalid syntax

**Comment by JasurFugen** [comment]
Please help guys!!!!!!!

**Comment by bitbrute** [comment]
@OthtiQ You are missing the `netifaces` module.
@JasurFugen You are trying to run EvilLimiter on Python 2.7, which is not supported.

Follow the [installation instructions](https://github.com/bitbrute/evillimiter/blob/master/README.md#Installation) carefully.
