### ISSUE TITLE
Nothing is being Blocked

### ISSUE THREAD

**Issue by wmhaganjr1013** [bitbrute/evillimiter#6]
Hello i have tried everything even reinstalling but nothing is being blocked and when i free i get error to flush network and i have to reboot to get menu back to try again

**Comment by bitbrute** [comment]
Does this issue persist if you specify the ```--flush``` flag?
```evillimiter --flush```

If that is the case, could you send me the output of this command:
```tc qdisc add dev [YOUR INTERFACE NAME] root handle 1:0 htb```
... replace [YOUR INTERFACE] name with the actual interface name ;).

**Comment by nico0709** [comment]
Hi,
I've installed Evil Limiter today, but block option is not working...

**Comment by ihateadmins** [comment]
it would be quiet useful if you give more detail on which Os usage, tried methods etc... It works well on a linux host machine

**Comment by ihateadmins** [comment]
it would be quiet useful if you give more detail on which Os usage, tried methods etc... It works well on a linux host machine

**Comment by wmhaganjr1013** [comment]
Sorry i got called into work Os was Kali Linux i will redownload and run
again tonight if i get home not so late tonight

**Comment by nico0709** [comment]
i'm using Kali, last distrib, I installed with git clone, i've no error message when i'm trying to block, but it doesn't work... :'(

**Comment by ihateadmins** [comment]
It works well with the latest Kali distr. Guys simply telling the Os won't get you anywhere. You have to provide more information(for example device name) and maybe logs

**Comment by ihateadmins** [comment]
It works well with the latest Kali distr. Guys simply telling the Os won't get you anywhere. You have to provide more information(for example device name, network) and maybe logs like a cap/pcap with wireshark

**Comment by leonardus** [comment]
@bitbrute I've noticed that both blocking and limiting work when the device attemps to connect to an address on the LAN (e.g. to the gateway), but not when the device attempts to connect to the internet (connecting to, for example, `github.com` works fine). The issue does persist with the `--flush` flag. Running `sudo tc qdisc add dev wlp0s20f0u7 root handle 1:0 htb` produced no output the first time, and `Error: Exclusivity flag on, cannot modify.` subsequent times.

**Comment by bitbrute** [comment]
I'm not sure if I understood you correctly. You said blocking and limiting does not work when the device attempts to connect to the internet, yet you wrote that it works fine for e.g. ```github.com```.
Make sure that the connection is truly IPv4. If you have IPv6 enabled in your router settings, some websites that support IPv6 will not be affected by EvilLimiter.

**Comment by leonardus** [comment]
Connecting to `github.com` works fine, as in, it is not blocked by evillimiter. IPv6 may be the culprit, however.

**Comment by bitbrute** [comment]
Oh, I see ;).
You could try to capture some packets and see whether or not the connection is IPv4 or IPv6.

**Comment by leonardus** [comment]
Yeah, looks like it's indeed IPv6. Connecting to `ipv6.icanhazip.com` is always successful on a blocked device, while `ipv4.icanhazip.com` is blocked by evillimiter.

**Comment by Eugejin** [comment]
It's doesn't work the block option. I did block my phone and still get internet connection. Why is that?
