### ISSUE TITLE
How to import in other projects / automate it?

### ISSUE THREAD

**Issue by trelljaret** [bitbrute/evillimiter#62]
I want to be able to use evillimiter in my python project.
Or if possible, is there any way to automate it? Is there any interface that I can use to interact with evillimiter (other than using expect and pexpect and stuff) ?

Please help, as the limit option does not work on my machine I would rather create something that:
searches for someone (based on mac address), blocks them, waits 20 seconds, flushes the whole thing (--flush), waits 10 seconds, repeat.

thanks.

**Comment by trelljaret** [comment]
I have setup a pexpect script to automate it already.
Anyway if there are interfaces that are usable right now please tell me. thanks.

**Comment by bitbrute** [comment]
As of now, EvilLimiter does not expose an API or interfaces to interact with. That would require the entire codebase to be refactored, since I didn't really focus on modularity during development.
However, you can still go through the code and use it for your project.
