### ISSUE TITLE
Command history (and quick access with ↑)

### ISSUE THREAD

**Issue by mp1994** [bitbrute/evillimiter#67]
You could implement the history of commands accessible with the upwards arrow (↑), as in the BASH shell (and/or Python). I guess it would be easy to implement this logging the command history and then catching the key press event when the ↑ is pressed. But I'm sure there's a library somewhere that implements this way better and faster.

**Comment by bitbrute** [comment]
That's a very cool idea!
I'll add it to the [wishlist](https://github.com/bitbrute/evillimiter/issues/63) and close this issuse.

Thanks!
