### ISSUE TITLE
Why isn't working on websites like google, youtube etc... ?

### ISSUE THREAD

**Issue by NailitoX** [bitbrute/evillimiter#68]
i tested on many computers and smartphones but every time google and youtube isn't working

**Comment by leonardus** [comment]
You're probably connecting to them over IPv6, which evillimiter doesn't currently support.

**Comment by NailitoX** [comment]
So how to switch to IPv4 then ?

**Comment by f1vefour** [comment]
You must do it manually with each device or do it system wide with your router.
