### ISSUE TITLE
AttributeError: module 'netifaces' has no attribute 'interfaces'

### ISSUE THREAD

**Issue by sangbatosai-code5** [bitbrute/evillimiter#69]
I Have error when running EvilLimiter. Can fixed it?

**Traceback (most recent call last):**

  _File "/usr/local/bin/evillimiter", line 33, in <module>
    sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter')())_

  _File "/usr/local/lib/python3.8/dist-packages/evillimiter-1.5.0-py3.8.egg/evillimiter/evillimiter.py", line 167, in run
    args = process_arguments(args)_

  _File "/usr/local/lib/python3.8/dist-packages/evillimiter-1.5.0-py3.8.egg/evillimiter/evillimiter.py", line 76, in process_arguments
    if not netutils.exists_interface(interface):_

  _File "/usr/local/lib/python3.8/dist-packages/evillimiter-1.5.0-py3.8.egg/evillimiter/networking/utils.py", line 54, in exists_interface
    return interface in netifaces.interfaces()_

**AttributeError: module 'netifaces' has no attribute 'interfaces'**

**Comment by sangbatosai-code5** [comment]
**SOLVED**
I just download **Netifaces 0.10.9** 
Because codeAttributeError: module 'netifaces' has no attribute 'gateways'  'interfaces' only run with this versions. 

**Installation Download**
_https://pypi.org/project/netifaces/0.10.0/_

**Comment by Wegito** [comment]
did an ImportError faced you ? 
an ImportError no Setuptools module pops all the time

**Comment by sangbatosai-code5** [comment]
No didn't bro, lets get this way. My problem is solved

> **SOLVED**
> I just download **Netifaces 0.10.9**
> Because codeAttributeError: module 'netifaces' has no attribute 'gateways' 'interfaces' only run with this versions.
> 
> **Installation Download**
> _https://pypi.org/project/netifaces/0.10.0/_
