### ISSUE TITLE
Error: qdisc root handle could not be created 2020

### ISSUE THREAD

**Issue by iRedddy** [bitbrute/evillimiter#75]
> I'm currently using Kali Linux from the microsoft store. I've used both the GUI and the command prompt verison. Any fix you guys have come acrossed? At this time, i'm using Evil Limiter V1.5.0. Older versions like 1.1.0 still shows the same error. Don't say do sudo evillimiter --flush because i've done it already and it still says the error in the title. All ideas except flushing will help.

**Comment by bitbrute** [comment]
EvilLimiter does not support Kali Linux running on WSL (Microsoft store). See #64 
Run Kali Linux inside a virtual machine or natively in order to use EvilLimiter.
