### ISSUE TITLE
[Errno 2]

### ISSUE THREAD

**Issue by ghost** [bitbrute/evillimiter#84]
I got this error message when  I run evillimiter ? 
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

how to fix it?

**Comment by leonardus** [comment]
What operating system are you on?

**Comment by ghost** [comment]
> operating system

Linux

**Comment by steph232** [comment]
Same here, everything was fine until I ran the system update **(Kali Linux 2020.3 / 64bit)** to version **2020.4** and boom, 4 more tools besides evillimiter prints me relative to **library("c")**  :

Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 33, in <module>
    sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter')())
  File "/usr/local/bin/evillimiter", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/**python3.9**/**importlib**/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/**python3.9**/**importlib**/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/evillimiter.py", line 9, in <module>
    import evillimiter.networking.utils as netutils
  File "/usr/local/lib/**python3.9**/dist-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/networking/utils.py", line 3, in <module>
    from scapy.all import ARP, sr1 # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/**scapy**/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/lib/python3/dist-packages/**scapy**/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/**ctypes**/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/**ctypes**/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/**ctypes**/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
**FileNotFoundError: [Errno 2] No such file or directory**: **b'liblibc.a'**

**Comment by ghost** [comment]
It was working very well but after the system update (Parrot OS) I get the same error. I tried reinstalling but it did not work.

**Comment by boooyab** [comment]
Any solution guys ....?

**Comment by dijey099** [comment]
I have the same problem...after updating to 2020.4, it gets error.
So, I 've download the image file of Kali linux 2020.4 and installing it directly, and it works. Then I've upgrade again by typing "apt update && upgrade" and it gets errror again.
Conclusion: the new version of python (Python 3.9) is the cause.

**Comment by ghost** [comment]
> Any solution guys ....?

Fix { Error2}

1.  cd /usr/lib/x86_64-linux-gnu/
2. ln -s -f libc.a liblibc.a

**Comment by ghost** [comment]
> It was working very well but after the system update (Parrot OS) I get the same error. I tried reinstalling but it did not work.

Fix { Error2}

1.  cd /usr/lib/x86_64-linux-gnu/
2. ln -s -f libc.a liblibc.a

**Comment by ghost** [comment]
> Same here, everything was fine until I ran the system update **(Kali Linux 2020.3 / 64bit)** to version **2020.4** and boom, 4 more tools besides evillimiter prints me relative to **library("c")**  :
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/bin/evillimiter", line 33, in <module>
> 
>     sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter')())
> 
>   File "/usr/local/bin/evillimiter", line 25, in importlib_load_entry_point
> 
>     return next(matches).load()
> 
>   File "/usr/lib/**python3.9**/**importlib**/metadata.py", line 77, in load
> 
>     module = import_module(match.group('module'))
> 
>   File "/usr/lib/**python3.9**/**importlib**/__init__.py", line 127, in import_module
> 
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> 
>   File "/usr/local/lib/python3.9/dist-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/evillimiter.py", line 9, in <module>
> 
>     import evillimiter.networking.utils as netutils
> 
>   File "/usr/local/lib/**python3.9**/dist-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/networking/utils.py", line 3, in <module>
> 
>     from scapy.all import ARP, sr1 # pylint: disable=no-name-in-module
> 
>   File "/usr/lib/python3/dist-packages/**scapy**/all.py", line 16, in <module>
> 
>     from scapy.arch import *
> 
>   File "/usr/lib/python3/dist-packages/**scapy**/arch/__init__.py", line 27, in <module>
> 
>     from scapy.arch.bpf.core import get_if_raw_addr
> 
>   File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 30, in <module>
> 
>     LIBC = cdll.LoadLibrary(find_library("libc"))
> 
>   File "/usr/lib/python3.9/**ctypes**/util.py", line 341, in find_library
> 
>     _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
> 
>   File "/usr/lib/python3.9/**ctypes**/util.py", line 147, in _findLib_gcc
> 
>     if not _is_elf(file):
> 
>   File "/usr/lib/python3.9/**ctypes**/util.py", line 99, in _is_elf
> 
>     with open(filename, 'br') as thefile:
> 
> **FileNotFoundError: [Errno 2] No such file or directory**: **b'liblibc.a'**

Fix { Error2}

1.  cd /usr/lib/x86_64-linux-gnu/
2. ln -s -f libc.a liblibc.a

**Comment by ghost** [comment]
> > It was working very well but after the system update (Parrot OS) I get the same error. I tried reinstalling but it did not work.
> 
> Fix { Error2}
> 
> 1.  cd /usr/lib/x86_64-linux-gnu/
> 2. ln -s -f libc.a liblibc.a
> 

Thanks. Now it is working again.
